// This file is auto-generated by ./bin/rails generate stimulus
// or manually managed if not using the generator.

import { application } from "controllers/application"

import UploadController from "controllers/upload_controller"
application.register("upload", UploadController)
